name: Refresh MPD Every Minute

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Browser Fetch
        run: |
          for i in {1..20}; do
            curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
              -H "Referer: https://mpdchecker.updatesbyrahul.site/" \
              "https://mpdchecker.updatesbyrahul.site/update-mpd.php" \
              > /dev/null
            sleep 3
          done
